// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAFDoSyASP5zrhs1L1jJkasIn6z9nCmHI',
    appId: '1:593268085808:web:7ed4a80c7421f4fc7649f5',
    messagingSenderId: '593268085808',
    projectId: 'cmsc23-todo-app-cbcontaoi',
    authDomain: 'cmsc23-todo-app-cbcontaoi.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-cbcontaoi.appspot.com',
    measurementId: 'G-V876TV0WEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvnP2H6MDxo5kWS6959flCtDp3nTFj2XU',
    appId: '1:593268085808:android:34221718fcc4bd4d7649f5',
    messagingSenderId: '593268085808',
    projectId: 'cmsc23-todo-app-cbcontaoi',
    storageBucket: 'cmsc23-todo-app-cbcontaoi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv7_42yV4OHD9ym3ESqJrUv_2vL6sxVbI',
    appId: '1:593268085808:ios:1680291fe2114cf07649f5',
    messagingSenderId: '593268085808',
    projectId: 'cmsc23-todo-app-cbcontaoi',
    storageBucket: 'cmsc23-todo-app-cbcontaoi.appspot.com',
    iosClientId: '593268085808-8fjl7f687sciupgr2uphgnfn9thied20.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv7_42yV4OHD9ym3ESqJrUv_2vL6sxVbI',
    appId: '1:593268085808:ios:1680291fe2114cf07649f5',
    messagingSenderId: '593268085808',
    projectId: 'cmsc23-todo-app-cbcontaoi',
    storageBucket: 'cmsc23-todo-app-cbcontaoi.appspot.com',
    iosClientId: '593268085808-8fjl7f687sciupgr2uphgnfn9thied20.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
