// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcXb0CMkKHboiDMD4wmz3nNTq6RzPjAxE',
    appId: '1:850221367044:web:5b0ddb5f9d5d8ef6c85a51',
    messagingSenderId: '850221367044',
    projectId: 'cmsc23-project-contaoi',
    authDomain: 'cmsc23-project-contaoi.firebaseapp.com',
    storageBucket: 'cmsc23-project-contaoi.appspot.com',
    measurementId: 'G-F4G525VDGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQGugOBm6IVl9RjzjXK565vIwdeQSe1kA',
    appId: '1:850221367044:android:6d5f9156cb152e83c85a51',
    messagingSenderId: '850221367044',
    projectId: 'cmsc23-project-contaoi',
    storageBucket: 'cmsc23-project-contaoi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPaGbkEHCYOnO9TiTEktRtrX2B_-m8_a4',
    appId: '1:850221367044:ios:edd304c4e70cf901c85a51',
    messagingSenderId: '850221367044',
    projectId: 'cmsc23-project-contaoi',
    storageBucket: 'cmsc23-project-contaoi.appspot.com',
    iosClientId: '850221367044-gsacjanap0hliv0mdjb3kjtkh5qlsm3j.apps.googleusercontent.com',
    iosBundleId: 'com.onatcipli.networkUpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPaGbkEHCYOnO9TiTEktRtrX2B_-m8_a4',
    appId: '1:850221367044:ios:edd304c4e70cf901c85a51',
    messagingSenderId: '850221367044',
    projectId: 'cmsc23-project-contaoi',
    storageBucket: 'cmsc23-project-contaoi.appspot.com',
    iosClientId: '850221367044-gsacjanap0hliv0mdjb3kjtkh5qlsm3j.apps.googleusercontent.com',
    iosBundleId: 'com.onatcipli.networkUpp',
  );
}
